pipeline {
    agent any
     label 'docker'

    stage('Docker-backend build and run') {
            steps {
                sh 'cd api && docker build -f Dockerfile -t backend .'

                sh 'docker run -d -p 80:8080 backend'
            }
        }


    }



